from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import httpx

XAI_CHAT_URL = "https://api.x.ai/v1/chat/completions"

SYSTEM_PROMPT = """\
You are a senior software engineer onboarding a new team member.
Based on the codebase summary provided, write a clear and engaging spoken onboarding script.

Rules:
- Maximum 200 words. This is a hard limit. Count carefully.
- Write in natural spoken English, as if you are talking out loud to a new developer.
- Do NOT use markdown, bullet points, headers, or any formatting — plain prose only.
- Cover: what the project does, how it is structured, the main technologies used, where the key entry points are, and one practical tip for getting started.
- Be warm, direct, and human. Avoid corporate jargon.
- End with a single sentence of encouragement."""


def count_words(text: str) -> int:
    return len(text.split())


def generate_script(summary: str, api_key: str) -> str:
    """Call Grok to generate the onboarding script. Retries once if over 200 words."""
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    messages: list[dict] = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": f"Codebase summary:\n\n{summary}"},
    ]

    resp = httpx.post(
        XAI_CHAT_URL,
        json={"model": "grok-4", "max_tokens": 400, "messages": messages, "stream": False},
        headers=headers,
        timeout=60.0,
    )
    if resp.status_code != 200:
        raise RuntimeError(f"Grok API error {resp.status_code}: {resp.text}")

    script = resp.json()["choices"][0]["message"]["content"].strip()
    if not script:
        raise RuntimeError("Grok returned an empty script.")

    word_count = count_words(script)
    if word_count > 200:
        messages.append({"role": "assistant", "content": script})
        messages.append({
            "role": "user",
            "content": (
                f"That was {word_count} words. Please shorten it to strictly under 200 words "
                "while keeping all key information."
            ),
        })
        resp2 = httpx.post(
            XAI_CHAT_URL,
            json={"model": "grok-4", "max_tokens": 400, "messages": messages, "stream": False},
            headers=headers,
            timeout=60.0,
        )
        if resp2.status_code == 200:
            script = resp2.json()["choices"][0]["message"]["content"].strip()

    return script


def save_onboarding_md(script: str, output_path: Path, overwrite: bool = False) -> bool:
    """Write onboarding.md. Prompts before overwriting unless overwrite=True. Returns False if aborted."""
    if output_path.exists() and not overwrite:
        answer = input("onboarding.md already exists. Overwrite? [y/N] ").strip().lower()
        if answer != "y":
            return False

    word_count = count_words(script)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")
    content = (
        f"# Onboarding\n\n"
        f"> Auto-generated by GrokCode on {now} UTC\n"
        f"> Word count: {word_count}\n\n"
        f"{script}\n\n"
        f"---\n\n"
        f"*Generated with [GrokCode](https://github.com/gravity9/grokcode) powered by xAI Grok*\n"
    )
    output_path.write_text(content, encoding="utf-8")
    return True
