from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import pytest
import respx
from httpx import Response

from grokcode.onboarding.script import count_words, generate_script, save_onboarding_md

XAI_CHAT = "https://api.x.ai/v1/chat/completions"


def _make_response(text: str) -> Response:
    return Response(
        200,
        json={
            "choices": [{"message": {"role": "assistant", "content": text}, "finish_reason": "stop"}],
            "usage": {"prompt_tokens": 50, "completion_tokens": 20},
        },
    )


def test_count_words() -> None:
    assert count_words("hello world") == 2
    assert count_words("  one  two  three  ") == 3
    assert count_words("") == 0


@respx.mock
def test_generate_script_returns_text() -> None:
    respx.post(XAI_CHAT).mock(return_value=_make_response("Welcome to the project. " * 5))
    result = generate_script("some summary", "test-key")
    assert "Welcome" in result


@respx.mock
def test_generate_script_retries_when_over_200_words() -> None:
    long_text = " ".join(["word"] * 210)
    short_text = " ".join(["word"] * 150)

    call_count = 0

    def side_effect(request, **kwargs):
        nonlocal call_count
        call_count += 1
        return _make_response(long_text if call_count == 1 else short_text)

    respx.post(XAI_CHAT).mock(side_effect=side_effect)
    result = generate_script("summary", "test-key")
    assert call_count == 2
    assert count_words(result) == 150


@respx.mock
def test_generate_script_raises_on_api_error() -> None:
    respx.post(XAI_CHAT).mock(return_value=Response(500, text="Internal Server Error"))
    with pytest.raises(RuntimeError, match="Grok API error 500"):
        generate_script("summary", "test-key")


@respx.mock
def test_generate_script_raises_on_empty_response() -> None:
    respx.post(XAI_CHAT).mock(return_value=_make_response(""))
    with pytest.raises(RuntimeError, match="empty"):
        generate_script("summary", "test-key")


def test_save_onboarding_md_creates_file(tmp_path: Path) -> None:
    output = tmp_path / "onboarding.md"
    result = save_onboarding_md("This is my script.", output, overwrite=True)
    assert result is True
    assert output.exists()
    content = output.read_text()
    assert "# Onboarding" in content
    assert "Auto-generated by GrokCode" in content
    assert "Word count:" in content
    assert "This is my script." in content
    assert "GrokCode" in content


def test_save_onboarding_md_aborts_when_user_says_no(tmp_path: Path) -> None:
    output = tmp_path / "onboarding.md"
    output.write_text("old content")
    with patch("builtins.input", return_value="n"):
        result = save_onboarding_md("new script", output, overwrite=False)
    assert result is False
    assert output.read_text() == "old content"


def test_save_onboarding_md_overwrites_when_user_says_yes(tmp_path: Path) -> None:
    output = tmp_path / "onboarding.md"
    output.write_text("old content")
    with patch("builtins.input", return_value="y"):
        result = save_onboarding_md("new script", output, overwrite=False)
    assert result is True
    assert "new script" in output.read_text()


def test_save_onboarding_md_overwrite_flag_skips_prompt(tmp_path: Path) -> None:
    output = tmp_path / "onboarding.md"
    output.write_text("old content")
    result = save_onboarding_md("new script", output, overwrite=True)
    assert result is True
    assert "new script" in output.read_text()


def test_save_onboarding_md_word_count_in_header(tmp_path: Path) -> None:
    output = tmp_path / "onboarding.md"
    script = "one two three four five"
    save_onboarding_md(script, output, overwrite=True)
    content = output.read_text()
    assert "Word count: 5" in content
